name: Compile LaTeX and Publish PDF

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set timezone from latexmkrc
        run: |
          TZ=$(grep -oP "(?<=\\\$ENV\{'TZ'\}=')[^']+" latexmkrc)
          echo "TZ=$TZ" >> $GITHUB_ENV

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            main.tex
            Integration/Leibniz_Integral_Rule.tex
          extra_system_packages: tzdata
        env:
          TZ: Europe/London

      - name: Deploy PDF to pdf branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan pdf-tmp
          git reset
          git add main.pdf Leibniz_Integral_Rule.pdf
          git commit -m "Update PDF"
          git push origin pdf-tmp:pdf --force

  cleanup:
    runs-on: ubuntu-latest
    needs: build
    if: always()

    steps:
      - name: Delete failed workflow runs
        run: |
          (
            gh run list --repo $REPO --status failure --json databaseId -q '.[].databaseId'
            gh run list --repo $REPO --status canceled --json databaseId -q '.[].databaseId'
          ) | sort | uniq | tail -n +2 | \
          xargs -I {} gh run delete --repo $REPO {}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
